#include "local_voice_pipeline.h"

#include <chrono>
#include <cmath>
#include <condition_variable>
#include <cstdint>
#include <iostream>
#include <mutex>
#include <string>
#include <vector>

namespace {

class FakeAsr final : public cockpit::AsrPort {
public:
    void reset() override {
        ++reset_count;
        accepted_samples = 0;
    }

    bool acceptPcm(const int16_t* samples, std::size_t sample_count,
                   cockpit::PcmFormat format) override {
        if (!samples || format.sample_rate != 16000 || format.channels != 1) return false;
        ++pcm_calls;
        accepted_samples += sample_count;
        return true;
    }

    std::string finalText() override {
        ++final_count;
        return accepted_samples == 1600 ? "打开阅读灯" : "";
    }

    int reset_count{0};
    int pcm_calls{0};
    int final_count{0};
    std::size_t accepted_samples{0};
};

class FakeConversation final : public cockpit::ConversationPort {
public:
    void submitVoiceText(std::string text) override {
        {
            std::lock_guard<std::mutex> lock(mutex);
            submitted.push_back(std::move(text));
        }
        cv.notify_all();
    }

    bool waitForSubmission(std::chrono::milliseconds timeout) {
        std::unique_lock<std::mutex> lock(mutex);
        return cv.wait_for(lock, timeout, [this] { return !submitted.empty(); });
    }

    std::mutex mutex;
    std::condition_variable cv;
    std::vector<std::string> submitted;
};

class FakeTts final : public cockpit::TtsPort {
public:
    void interrupt() override { ++interrupt_count; }
    int interrupt_count{0};
};

int fail(const char* reason) {
    std::cerr << "[TestLocalVoicePipeline] " << reason << '\n';
    return 1;
}

}  // namespace

int main() {
    FakeAsr asr;
    FakeConversation conversation;
    FakeTts tts;
    cockpit::LocalVoicePipeline pipeline(asr, conversation, tts);
    if (!pipeline.start()) return fail("pipeline did not start");

    // 100 ms of synthetic 16 kHz mono PCM. The fake ASR validates that it
    // receives exactly the samples generated by the simulated audio source.
    std::vector<int16_t> pcm(1600);
    for (std::size_t i = 0; i < pcm.size(); ++i) {
        pcm[i] = static_cast<int16_t>(std::sin(i * 0.1) * 12000.0);
    }

    const cockpit::PcmFormat format{16000, 1};
    pipeline.onCaptureStarted(format);
    if (!pipeline.onPcm(pcm.data(), pcm.size(), format)) return fail("synthetic PCM was dropped");
    pipeline.onCaptureEnded();

    if (!conversation.waitForSubmission(std::chrono::seconds(2))) {
        return fail("conversation did not receive final ASR text");
    }
    if (!pipeline.waitForIdle(std::chrono::seconds(2))) return fail("pipeline did not become idle");
    pipeline.stop();

    if (tts.interrupt_count != 1) return fail("TTS was not interrupted at capture start");
    if (asr.reset_count != 1 || asr.pcm_calls != 1 || asr.final_count != 1 ||
        asr.accepted_samples != pcm.size()) {
        return fail("ASR event sequence or PCM length is wrong");
    }
    if (conversation.submitted.size() != 1 || conversation.submitted.front() != "打开阅读灯") {
        return fail("unexpected text submitted to conversation runtime");
    }
    if (pipeline.droppedPcmChunks() != 0) return fail("unexpected PCM backpressure");

    std::cout << "[TestLocalVoicePipeline] fake PCM -> ASR -> conversation passed\n";
    return 0;
}
